spring:
  application:
    name: sgm-login
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sgm-login

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

swagger:
  version: 1.0
  description : Sistema de Autenticação por Token