spring:
  application:
    name: sgm-login

server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

swagger:
  version: 1.0
  description : APIs STUR ITR