spring:
  application:
    name: sgm-login
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sgm-login
    res:
      defaultMediaType: application/json

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: secret

swagger:
  version: 1.0
  description : Login OpenId